version: '3.9'

services:
  zuul:
    image: garystafford/storefront-zuul:1.0.0 # 3.0.0 failing
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - kafka
      - mongo
      - eureka
    environment:
      LOGGING_LEVEL_ROOT: DEBUG
      RIBBON_READTIMEOUT: 3000
      RIBBON_SOCKETTIMEOUT: 3000
      ZUUL_HOST_CONNECT_TIMEOUT_MILLIS: 3000
      ZUUL_HOST_CONNECT_SOCKET_MILLIS: 3000
    networks:
      - kafka-net

  eureka:
    image: garystafford/storefront-eureka:3.0.0
    ports:
      - target: 8761
        published: 8761
        protocol: tcp
        mode: host
    networks:
      - kafka-net

  mongo:
    image: mongo:4.4.5
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    networks:
      - kafka-net

  mongo_express:
    image: mongo-express:0.54.0
    depends_on:
      - mongo
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - kafka-net

  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    #    environment:
    #      ZOO_MY_ID: 1
    #      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "accounts.customer.change:1:1,fulfillment.order.change:1:1,orders.order.fulfill:1:1"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-net

  kafka_manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    networks:
      - kafka-net

networks:
  kafka-net: