version: '3.9'

services:
  accounts:
    image: garystafford/storefront-accounts:3.0.0
    ports:
      - target: 8080
        published: 8085
        protocol: tcp
        mode: host
    depends_on:
      - kafka
      - mongo
    environment:
      LOGGING_LEVEL_ROOT: DEBUG
    networks:
      - kafka-net

  orders:
    image: garystafford/storefront-orders:3.0.0
    ports:
      - target: 8080
        published: 8090
        protocol: tcp
        mode: host
    depends_on:
      - kafka
      - mongo
    environment:
      LOGGING_LEVEL_ROOT: DEBUG
    networks:
      - kafka-net

  fulfillment:
    image: garystafford/storefront-fulfillment:3.0.0
    ports:
      - target: 8080
        published: 8095
        protocol: tcp
        mode: host
    depends_on:
      - kafka
      - mongo
    environment:
      LOGGING_LEVEL_ROOT: DEBUG
    networks:
      - kafka-net

networks:
  kafka-net: