apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: fulfillment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fulfillment
  template:
    metadata:
      labels:
        app: fulfillment
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: fulfillment
        image: gcr.io/gke-confluent-atlas/storefront-fulfillment:gke-2.2.1
        resources:
          requests:
            memory: "250M"
            cpu: "100m"
          limits:
            memory: "400M"
            cpu: "250m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gke"
        - name: SERVER_SERVLET_CONTEXT-PATH
          value: "/fulfillment"
        - name: LOGGING_LEVEL_ROOT
          value: "INFO"
        - name: SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING
          value: "true"
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-atlas
              key: mongodb.uri.fulfillment
        - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
          valueFrom:
            secretKeyRef:
              name: confluent-cloud-kafka
              key: bootstrap.servers
        - name: SPRING_KAFKA_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: confluent-cloud-kafka
              key: ssl.endpoint.identification.algorithm
        - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
          valueFrom:
            configMapKeyRef:
              name: confluent-cloud-kafka
              key: sasl.mechanism
        - name: SPRING_KAFKA_PROPERTIES_REQUEST_TIMEOUT_MS
          valueFrom:
            configMapKeyRef:
              name: confluent-cloud-kafka
              key: request.timeout.ms
        - name: SPRING_KAFKA_PROPERTIES_RETRY_BACKOFF_MS
          valueFrom:
            configMapKeyRef:
              name: confluent-cloud-kafka
              key: retry.backoff.ms
        - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: confluent-cloud-kafka
              key: sasl.jaas.config
        - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: confluent-cloud-kafka
              key: security.protocol
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
