apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: fulfillment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fulfillment
  template:
    metadata:
      labels:
        app: fulfillment
        version: 3.0.0
    spec:
      containers:
        - name: fulfillment
          image: docker.io/garystafford/storefront-fulfillment:3.0.0-minikube
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "minikube"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "kafka-cluster-kafka-0.storefront-kafka-project.svc.cluster.local:9094"
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo.dev.svc.cluster.local:27017/fulfillment